USE master;
GO

IF (SELECT COUNT(*) FROM sys.server_audits WHERE name = 'MyAudit') > 0
BEGIN
	ALTER SERVER AUDIT MyAudit WITH (STATE = OFF)
	DROP SERVER AUDIT MyAudit;
END
IF (SELECT COUNT(*) FROM sys.server_audit_specifications WHERE name = 'MyAuditSpecification') > 0 DROP SERVER AUDIT SPECIFICATION MyAuditSpecification;
GO

CREATE SERVER AUDIT MyAudit
TO SECURITY_LOG
WITH ( QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE );
GO

CREATE SERVER AUDIT SPECIFICATION MyAuditSpecification
FOR SERVER AUDIT MyAudit
ADD (DATABASE_LOGOUT_GROUP);
GO

ALTER SERVER AUDIT SPECIFICATION MyAuditSpecification
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP);
GO

ALTER SERVER AUDIT MyAudit WITH (STATE = ON)
/*

CREATE DATABASE AUDIT SPECIFICATION [Audit_Spec_1]
FOR SERVER AUDIT [Srv_Audit_1]
ADD (INSERT ON OBJECT::[dbo].[Paradigm] BY [Exemplar]);
*/