USE master;
GO

IF DATABASEPROPERTYEX('CheckOption', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE CheckOption SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE CheckOption;
END
GO

CREATE DATABASE CheckOption;
GO

--ALTER DATABASE CheckOption SET RECOVERY SIMPLE;
--GO

USE CheckOption;
GO

CREATE TABLE A (Id int identity, A char(1), B int);
GO

INSERT INTO A SELECT 'A', 10;
INSERT INTO A SELECT 'B', 10;
INSERT INTO A SELECT 'C', 10;
INSERT INTO A SELECT 'D', 10;
INSERT INTO A SELECT 'A', 20;
INSERT INTO A SELECT 'B', 20;
INSERT INTO A SELECT 'C', 20;
INSERT INTO A SELECT 'D', 20;
GO

--VIEW_METADATA deals with client API
CREATE VIEW V1
AS
SELECT Id, A, B
FROM A
WHERE A = 'B'
WITH CHECK OPTION
GO

CREATE VIEW V2
AS
SELECT Id, A, B
FROM A
WHERE A = 'B'
GO

SELECT * FROM V1;
SELECT * FROM V2;
GO

-- will not work, because of WITH CHECK OPTION
UPDATE V1 SET A='Z' WHERE Id = 2
GO

-- will work
UPDATE V2 SET A='Z' WHERE Id = 2
GO

USE master;

IF DATABASEPROPERTYEX('CheckOption', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE CheckOption SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE CheckOption;
END
GO