USE master;
GO

IF DATABASEPROPERTYEX('FKExample', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE FKExample SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE FKExample;
END
GO

CREATE DATABASE FKExample;
GO

ALTER DATABASE FKExample SET RECOVERY SIMPLE;
GO

USE FKExample;
GO

CREATE TABLE table1 (
    id int PRIMARY KEY IDENTITY NOT NULL,
    name varchar(200)
)
GO

CREATE TABLE table2 (
    id int PRIMARY KEY IDENTITY NOT NULL,
    table2id int REFERENCES table1,
    table2id2 int FOREIGN KEY REFERENCES table1 (id),
    code char(20)
);
GO

ALTER TABLE table2 ADD table2id3 int;
ALTER TABLE table2 ADD CONSTRAINT fk_asdf FOREIGN KEY (table2id3) REFERENCES table1 (id)
GO

ALTER TABLE table2 ADD table2id4 int;
ALTER TABLE table2 ADD FOREIGN KEY (table2id4) REFERENCES table1 (id)
GO

USE master;
GO

IF DATABASEPROPERTYEX('FKExample', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE FKExample SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE FKExample;
END
GO