USE master;
GO

IF DATABASEPROPERTYEX('HintREADPAST', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE HintREADPAST SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE HintREADPAST;
END
GO

CREATE DATABASE HintREADPAST;
GO

USE HintREADPAST;
GO

CREATE TABLE Taco (ID INT IDENTITY PRIMARY KEY, Code CHAR(2), Price NUMERIC(7,2));
GO

INSERT Taco VALUES ('A', 1.0), ('B', 2.0), ('C', 3.0), ('D', 4.0);

BEGIN TRAN;
UPDATE TOP(1) Taco SET Price = Price + 1;
GO

----> IN ANOTHER WINDOW

	USE HintREADPAST;
	GO

	-- this sits there forever
	SELECT * FROM Taco;

	-- this ignores the locked record, returning everything else
	SELECT * FROM Taco WITH (READPAST);
	
	USE master;
	GO

ROLLBACK
GO

USE master;
GO

IF DATABASEPROPERTYEX('HintREADPAST', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE HintREADPAST SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE HintREADPAST;
END
GO