USE master;
GO

IF DATABASEPROPERTYEX('IndexedViews', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE IndexedViews SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE IndexedViews;
END
GO

CREATE DATABASE IndexedViews;
GO

ALTER DATABASE IndexedViews SET RECOVERY SIMPLE;
GO

USE IndexedViews;
GO

CREATE SEQUENCE Counter
START WITH 1
INCREMENT BY 1;
GO

CREATE TABLE A (Id int NOT NULL DEFAULT NEXT VALUE FOR Counter, A int DEFAULT 100*RAND(), B int DEFAULT 100*RAND());
CREATE TABLE B (Id int NOT NULL DEFAULT NEXT VALUE FOR Counter, A int DEFAULT 100*RAND(), B int DEFAULT 100*RAND());
GO

INSERT INTO A DEFAULT VALUES;
INSERT INTO B DEFAULT VALUES;
GO 100

SELECT * FROM A

INSERT INTO A SELECT NEXT VALUE FOR Counter, A, B FROM A;
GO 8

INSERT INTO B SELECT NEXT VALUE FOR Counter, A, B FROM B;
GO 8

ALTER SEQUENCE Counter
RESTART WITH 1;
GO

CREATE TABLE C (Id int NOT NULL DEFAULT NEXT VALUE FOR Counter, A int DEFAULT 100*RAND(), B int DEFAULT 100*RAND(), C AS Id + A);
CREATE TABLE D (Id int NOT NULL DEFAULT NEXT VALUE FOR Counter, A int DEFAULT 100*RAND(), B int DEFAULT 100*RAND(), C AS Id + A PERSISTED);
GO

INSERT INTO C DEFAULT VALUES;
INSERT INTO D DEFAULT VALUES;
GO 100

INSERT INTO C SELECT NEXT VALUE FOR Counter, A, B FROM C;
GO 8

INSERT INTO D SELECT NEXT VALUE FOR Counter, A, B FROM D;
GO 8

CHECKPOINT
GO

INSERT INTO A SELECT NEXT VALUE FOR Counter, A, B FROM A;
CHECKPOINT
GO 2

INSERT INTO B SELECT NEXT VALUE FOR Counter, A, B FROM B;
CHECKPOINT
GO 2

INSERT INTO C SELECT NEXT VALUE FOR Counter, A, B FROM C;
CHECKPOINT
GO 4

INSERT INTO D SELECT NEXT VALUE FOR Counter, A, B FROM D;
CHECKPOINT
GO 4

INSERT INTO A SELECT NEXT VALUE FOR Counter, A, B FROM A;
CHECKPOINT
GO 2

INSERT INTO B SELECT NEXT VALUE FOR Counter, A, B FROM B;
CHECKPOINT
GO 2

CREATE VIEW V1
WITH SCHEMABINDING
AS
SELECT Id , A , B FROM dbo.A;
GO

CREATE UNIQUE CLUSTERED INDEX CI_V1 on V1 (Id);
GO

DBCC FREEPROCCACHE
GO

SELECT A, B
FROM V1
WHERE Id = 21
GO

DBCC FREEPROCCACHE
GO

SELECT A, B
FROM V1
WITH (NOEXPAND)
WHERE Id = 21
GO

CREATE VIEW V2
WITH SCHEMABINDING
as
SELECT Id , A , B FROM dbo.A
UNION ALL
SELECT Id , A , B FROM dbo.B
GO

-- ERROR: cannot contains UNION
-- CREATE UNIQUE CLUSTERED INDEX CI_V2 on V2 (Id);
GO

CREATE VIEW V3
WITH SCHEMABINDING
as
SELECT Id , A , B, C FROM dbo.C
GO

CREATE UNIQUE CLUSTERED INDEX CI_V3 on V3 (Id);
GO

CREATE VIEW V4
WITH SCHEMABINDING
as
SELECT Id , A , B, C FROM dbo.D
GO

CREATE UNIQUE CLUSTERED INDEX CI_V4 on V4 (Id);
GO

-- double compute
SELECT TOP 10 Id , A , B, C FROM V3

-- single compute
SELECT TOP 10 Id , A , B, C FROM V4

USE master;
GO

IF DATABASEPROPERTYEX('IndexedViews', 'Status') IS NOT NULL DROP DATABASE IndexedViews;
GO