USE master;
GO

IF DATABASEPROPERTYEX('ID', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE ID SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE ID;
END
GO

CREATE DATABASE ForwardingPointers;
GO

SET NOCOUNT ON;
GO

CREATE DATABASE ID;
GO

ALTER DATABASE ID SET RECOVERY SIMPLE;
GO

USE ID;
GO

CREATE TABLE SequentialIdTable (A int identity, B uniqueidentifier DEFAULT NEWSEQUENTIALID());
CREATE TABLE IdTable (A int identity, B uniqueidentifier DEFAULT NEWID());
CREATE TABLE RowVersionTable (A int identity, B rowversion);
GO

INSERT SequentialIdTable DEFAULT VALUES
INSERT IdTable DEFAULT VALUES
INSERT RowVersionTable DEFAULT VALUES
GO 5

SELECT s.B as NEWSEQUENTIALID, i.B as NEWID, i.B as rowversion
FROM SequentialIdTable s
INNER JOIN IdTable i on s.A = i.A
INNER JOIN RowVersionTable r on s.A = r.A;
GO

USE master;
GO

IF DATABASEPROPERTYEX('ID', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE ID SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE ID;
END
GO