USE master;

ALTER DATABASE DATABASE_NAME SET EMERGENCY;
ALTER DATABASE DATABASE_NAME REBUILD LOG ON (Name=DATABASE_NAME_log, FILENAME='C:\_LOG\DATABASE_NAME.ldf');
ALTER DATABASE DATABASE_NAME SET MULTI_USER;
ALTER DATABASE DATABASE_NAME SET READ_ONLY;