USE master;
GO

IF DATABASEPROPERTYEX('RIDLookup', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE RIDLookup SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE RIDLookup;
END
GO

CREATE DATABASE RIDLookup;
GO

ALTER DATABASE RIDLookup SET RECOVERY SIMPLE;
GO

USE RIDLookup;
GO

CREATE TABLE Room (Id int IDENTITY, Name int DEFAULT (100 * RAND()), Position int DEFAULT (100 * RAND()));
GO

INSERT INTO Room DEFAULT VALUES;
GO 10

CREATE NONCLUSTERED INDEX NCI_Room ON Room (Name) INCLUDE (Id, Position);
GO

SELECT Id,
Name,
Position
FROM Room
WHERE Name = 15;
GO

DROP INDEX NCI_Room ON Room;
GO

USE master;
GO

IF DATABASEPROPERTYEX('RIDLookup', 'Status') IS NOT NULL DROP DATABASE RIDLookup;
GO