USE master;
GO

IF DATABASEPROPERTYEX('SymmetricKey', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE SymmetricKey SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE SymmetricKey;
END
GO

CREATE DATABASE SymmetricKey;
GO

--ALTER DATABASE SymmetricKey SET RECOVERY SIMPLE;
--GO

USE SymmetricKey;
GO

CREATE TABLE FactTable (
ID INT IDENTITY NOT NULL,
CaptureDate datetime2(0) NOT NULL,
EntityID INT NOT NULL,
StateID INT NOT NULL,
Value INT NOT NULL
);
GO

;WITH NumericValue(Tracker)
AS
(
	SELECT 1
	UNION ALL
	SELECT Tracker + 1
	FROM NumericValue
	WHERE Tracker < 20000
)
INSERT FactTable
SELECT DATEADD(day, (ABS(CHECKSUM(NEWID())) % (60)) * -1, CURRENT_TIMESTAMP), RAND(CHECKSUM(NEWID())) * 100, RAND(CHECKSUM(NEWID())) * 20, ABS(CHECKSUM(NEWID()))
FROM NumericValue 
OPTION (MAXRECURSION 20000)
GO

CREATE MASTER KEY ENCRYPTION
BY PASSWORD = 'Password!+';
GO

CREATE CERTIFICATE Cert1
WITH SUBJECT = 'New Data';
GO

CREATE SYMMETRIC KEY Key1 WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE Cert1;
GO

ALTER TABLE FactTable
ADD ValueSecure varbinary(256);
GO

OPEN SYMMETRIC KEY Key1
DECRYPTION BY CERTIFICATE Cert1;
GO

UPDATE FactTable
SET ValueSecure = EncryptByKey(Key_GUID('Key1'), CONVERT(varchar, Value));
GO

ALTER TABLE FactTable
DROP COLUMN Value;
GO

SELECT TOP 10 CaptureDate, ValueSecure, CAST(DecryptByKey(ValueSecure) AS int) as Value
FROM FactTable
ORDER BY CaptureDate DESC
GO

CLOSE SYMMETRIC KEY Key1;
GO

-- NULL
SELECT TOP 10 CaptureDate, ValueSecure, CAST(DecryptByKey(ValueSecure) AS int) as Value
FROM FactTable
ORDER BY CaptureDate DESC
GO

--CREATE CLUSTERED INDEX CI_FactTable_ID ON FactTable(ID)
--GO

--ALTER TABLE FactTable REBUILD WITH (DATA_COMPRESSION=ROW);
--GO

WITH
A([Year])
AS (
	SELECT DATEPART(year, CaptureDate) FROM FactTable
)
SELECT [Year]
FROM A
GROUP BY [Year]
ORDER BY [Year] DESC
GO

USE master;
GO

--BACKUP DATABASE SymmetricKey TO DISK='P:\SymmetricKey.bak' WITH FORMAT, STATS = 10, DESCRIPTION = 'FULL';
--GO

--ALTER DATABASE SymmetricKey SET RECOVERY SIMPLE;
--GO

--RESTORE DATABASE SymmetricKey FROM DISK='P:\SymmetricKey.bak' WITH STATS = 10;
--GO

IF DATABASEPROPERTYEX('SymmetricKey', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE SymmetricKey SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE SymmetricKey;
END
GO