USE master;
GO

IF DATABASEPROPERTYEX('ViewMetadata', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE ViewMetadata SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE ViewMetadata;
END
GO

CREATE DATABASE ViewMetadata;
GO

ALTER DATABASE ViewMetadata SET RECOVERY SIMPLE;
GO

USE ViewMetadata;
GO

CREATE TABLE A (Id int identity, A int, B char(10), C as A + 2);
GO

INSERT INTO A SELECT 1, 'a'
INSERT INTO A SELECT 2, 'b'
INSERT INTO A SELECT 3, 'c'
INSERT INTO A SELECT 4, 'd'
GO

--VIEW_METADATA deals with client API
CREATE VIEW V1
WITH VIEW_METADATA
AS
SELECT * FROM A;
GO

CREATE VIEW V2
WITH VIEW_METADATA
AS
SELECT ID, A, B FROM A;
GO

SELECT * FROM V1;
SELECT * FROM V2;
GO

ALTER TABLE A DROP COLUMN C;
GO

-- will fail-- but NOT because of VIEW_METADATA-- that's for client API!
--SELECT * FROM V1;
-- will work fine
SELECT * FROM V2;
GO

-- fixed V1
sp_refreshview V1
GO

SELECT * FROM V1;
GO

USE master;

IF DATABASEPROPERTYEX('ViewMetadata', 'Status') IS NOT NULL
BEGIN
	ALTER DATABASE ViewMetadata SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE ViewMetadata;
END
GO